stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: my-image-name # Replace with your image name
  IMAGE_TAG: latest # Replace with your desired tag or use $CI_COMMIT_REF_SLUG for dynamic tagging

services:
  - docker:dind

before_script:
  #- docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD # Replace with your registry if not Docker Hub
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_image:
  image: docker:latest
  stage: build
  script:
    #- docker build -t $IMAGE_TAG .
    #- docker build . -t jiechau/ubuntu:22.04 -t jiechau/ubuntu:latest -t jiechau/ubuntu
    - docker build . -t $CI_REGISTRY_IMAGE:22.04 -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE
    #
    - docker push $CI_REGISTRY_IMAGE
    #- docker push jiechau/ubuntu:22.04
  only:
    - main
