stages:
  - build_gitlab
  - build_dockerhub

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: my-image-name # Replace with your image name
  IMAGE_TAG: latest # Replace with your desired tag or use $CI_COMMIT_REF_SLUG for dynamic tagging

services:
  - docker:dind

do_gitlab:
  image: docker:latest
  stage: build_gitlab
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -t $CI_REGISTRY_IMAGE:22.04 -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE
    #
    - docker push $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE:22.04
  only:
    - main

do_dockerhub:
  image: docker:latest
  stage: build_dockerhub
  script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD 
    - docker build . -t jiechau/ubuntu:22.04 -t jiechau/ubuntu:latest -t jiechau/ubuntu
    #
    - docker push jiechau/ubuntu
    - docker push jiechau/ubuntu:22.04
  only:
    - main
