stages:
  - build
  - push

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - echo 'aaaaaaaa'
  - echo $CI_COMMIT_REF_SLUG
  - echo 'bbbbbbbb'

build_image:
  stage: build
  script:
    #- docker build -t $IMAGE_TAG .
    - docker build . -t jiechau/ubuntu:22.04 -t jiechau/ubuntu:latest -t jiechau/ubuntu
  only:
    - main

push_to_registry:
  stage: push
  script:
    #- docker push $IMAGE_TAG
    - docker push jiechau/ubuntu
    - docker push jiechau/ubuntu:22.04
  only:
    - main
