apiVersion: v1
kind: Pod
metadata:
  name: my-shell
  namespace: aiapi
spec:
  containers:
  - name: my-shell
    image: jiechau/ubuntu:22.04
    #command: ["/bin/bash"]
    command: ["/bin/bash", "-c", "tail -f /dev/null"]
    imagePullPolicy: Always

